export const FRUIT_CATALOG = [
  {
    key: "rocket",
    name: "Rocket",
    namePt: "Foguete",
    aliases: ["rocket", "foguete"],
    rarity: "Common",
    type: "Natural",
    roles: ["farm"],
    description: "Fruta simples para mobilidade e inicio de jornada.",
    beliPrice: 5000,
    permRobuxPrice: 50,
    value: 5000
  },
  {
    key: "spin",
    name: "Spin",
    namePt: "Giro",
    aliases: ["spin", "giro"],
    rarity: "Common",
    type: "Natural",
    roles: ["farm"],
    description: "Opcao basica com foco em movimentacao e controle leve.",
    beliPrice: 7500,
    permRobuxPrice: 75,
    value: 7500
  },
  {
    key: "blade",
    name: "Blade",
    namePt: "Lamina",
    aliases: ["blade", "lamina", "sword"],
    rarity: "Common",
    type: "Natural",
    roles: ["farm", "pvp"],
    description: "Boa para usuarios iniciantes que gostam de combate direto.",
    beliPrice: 30000,
    permRobuxPrice: 100,
    value: 50000
  },
  {
    key: "spring",
    name: "Spring",
    namePt: "Mola",
    aliases: ["spring", "mola"],
    rarity: "Common",
    type: "Natural",
    roles: ["farm"],
    description: "Mobilidade divertida, mas fora do meta atual.",
    beliPrice: 60000,
    permRobuxPrice: 180,
    value: 60000
  },
  {
    key: "bomb",
    name: "Bomb",
    namePt: "Bomba",
    aliases: ["bomb", "bomba"],
    rarity: "Common",
    type: "Natural",
    roles: ["farm", "pvp"],
    description: "Explosiva e barata, boa para comecar.",
    beliPrice: 80000,
    permRobuxPrice: 220,
    value: 80000
  },
  {
    key: "smoke",
    name: "Smoke",
    namePt: "Fumaca",
    aliases: ["smoke", "fumaca", "fumaça"],
    rarity: "Common",
    type: "Elemental",
    roles: ["farm"],
    description: "Uma logia util no early game.",
    beliPrice: 100000,
    permRobuxPrice: 250,
    value: 100000
  },
  {
    key: "spike",
    name: "Spike",
    namePt: "Espinho",
    aliases: ["spike", "espinho"],
    rarity: "Common",
    type: "Natural",
    roles: ["pvp"],
    description: "Fruta simples com potencial surpresa em PvP.",
    beliPrice: 180000,
    permRobuxPrice: 380,
    value: 180000
  },
  {
    key: "flame",
    name: "Flame",
    namePt: "Chama",
    aliases: ["flame", "chama", "fogo"],
    rarity: "Uncommon",
    type: "Elemental",
    roles: ["farm", "pvp"],
    description: "Boa area e dano consistente.",
    beliPrice: 250000,
    permRobuxPrice: 550,
    value: 250000
  },
  {
    key: "falcon",
    name: "Falcon",
    namePt: "Falcao",
    aliases: ["falcon", "falcao", "falcão", "eagle", "aguia", "águia"],
    rarity: "Uncommon",
    type: "Beast",
    roles: ["farm"],
    description: "Voar cedo ajuda, mas o meta passa longe dela.",
    beliPrice: 300000,
    permRobuxPrice: 650,
    value: 800000
  },
  {
    key: "ice",
    name: "Ice",
    namePt: "Gelo",
    aliases: ["ice", "gelo"],
    rarity: "Uncommon",
    type: "Elemental",
    roles: ["farm", "pvp"],
    description: "Excelente crowd control e utilidade geral.",
    beliPrice: 350000,
    permRobuxPrice: 750,
    value: 550000
  },
  {
    key: "sand",
    name: "Sand",
    namePt: "Areia",
    aliases: ["sand", "areia"],
    rarity: "Uncommon",
    type: "Elemental",
    roles: ["farm", "pvp"],
    description: "Boa opcao intermediaria com dano decente.",
    beliPrice: 420000,
    permRobuxPrice: 850,
    value: 420000
  },
  {
    key: "dark",
    name: "Dark",
    namePt: "Escuridao",
    aliases: ["dark", "escuridao", "escuridão"],
    rarity: "Uncommon",
    type: "Elemental",
    roles: ["pvp", "support"],
    description: "Controle forte e combos perigosos.",
    beliPrice: 500000,
    permRobuxPrice: 950,
    value: 400000
  },
  {
    key: "diamond",
    name: "Diamond",
    namePt: "Diamante",
    aliases: ["diamond", "diamante"],
    rarity: "Uncommon",
    type: "Natural",
    roles: ["support", "pvp"],
    description: "Defensiva, niche e subestimada.",
    beliPrice: 600000,
    permRobuxPrice: 1000,
    value: 1000000
  },
  {
    key: "light",
    name: "Light",
    namePt: "Luz",
    aliases: ["light", "luz"],
    rarity: "Rare",
    type: "Elemental",
    roles: ["farm", "pvp", "travel"],
    description: "Muito usada para farm e mobilidade.",
    beliPrice: 650000,
    permRobuxPrice: 1100,
    value: 800000
  },
  {
    key: "rubber",
    name: "Rubber",
    namePt: "Borracha",
    aliases: ["rubber", "borracha", "gomu"],
    rarity: "Rare",
    type: "Natural",
    roles: ["pvp"],
    description: "Divertida e com potencial em mains especificos.",
    beliPrice: 750000,
    permRobuxPrice: 1200,
    value: 700000
  },
  {
    key: "ghost",
    name: "Ghost",
    namePt: "Fantasma",
    aliases: ["ghost", "fantasma", "revive", "ressurreicao"],
    rarity: "Rare",
    type: "Natural",
    roles: ["farm", "support"],
    description: "Utilidade unica e boa para grind.",
    beliPrice: 940000,
    permRobuxPrice: 1275,
    value: 800000
  },
  {
    key: "magma",
    name: "Magma",
    namePt: "Magma",
    aliases: ["magma"],
    rarity: "Rare",
    type: "Elemental",
    roles: ["farm", "pvp", "sea-events"],
    description: "Uma das melhores frutas para farm marinho e dano bruto.",
    beliPrice: 960000,
    permRobuxPrice: 1300,
    value: 1150000
  },
  {
    key: "quake",
    name: "Quake",
    namePt: "Tremor",
    aliases: ["quake", "tremor", "gura"],
    rarity: "Legendary",
    type: "Natural",
    roles: ["pvp"],
    description: "Impacto forte, excelente em combos e lutas.",
    beliPrice: 1000000,
    permRobuxPrice: 1500,
    value: 1000000
  },
  {
    key: "buddha",
    name: "Buddha",
    namePt: "Buda",
    aliases: ["buddha", "buda"],
    rarity: "Legendary",
    type: "Beast",
    roles: ["farm", "raid", "support"],
    description: "Rainha do farm e de raids no meta geral.",
    beliPrice: 1200000,
    permRobuxPrice: 1650,
    value: 10000000
  },
  {
    key: "love",
    name: "Love",
    namePt: "Amor",
    aliases: ["love", "amor"],
    rarity: "Legendary",
    type: "Natural",
    roles: ["pvp", "support"],
    description: "Charmosa e forte nas maos certas.",
    beliPrice: 1300000,
    permRobuxPrice: 1700,
    value: 1500000
  },
  {
    key: "spider",
    name: "Spider",
    namePt: "Aranha",
    aliases: ["spider", "aranha", "string"],
    rarity: "Legendary",
    type: "Natural",
    roles: ["pvp"],
    description: "Muito util para combos e arena.",
    beliPrice: 1500000,
    permRobuxPrice: 1800,
    value: 1500000
  },
  {
    key: "sound",
    name: "Sound",
    namePt: "Som",
    aliases: ["sound", "som"],
    rarity: "Legendary",
    type: "Natural",
    roles: ["support", "pvp"],
    description: "Boa presenca em grupo e dano decente.",
    beliPrice: 1700000,
    permRobuxPrice: 1900,
    value: 2500000
  },
  {
    key: "phoenix",
    name: "Phoenix",
    namePt: "Fenix",
    aliases: ["phoenix", "fenix", "fênix"],
    rarity: "Legendary",
    type: "Beast",
    roles: ["support", "pvp"],
    description: "Cura, sustain e valor de utilidade alto.",
    beliPrice: 1800000,
    permRobuxPrice: 2000,
    value: 2750000
  },
  {
    key: "portal",
    name: "Portal",
    namePt: "Portal",
    aliases: ["portal", "door", "porta"],
    rarity: "Legendary",
    type: "Natural",
    roles: ["travel", "support", "pvp"],
    description: "Mobilidade absurda e muito util em equipes.",
    beliPrice: 1900000,
    permRobuxPrice: 2000,
    value: 10000000
  },
  {
    key: "rumble",
    name: "Rumble",
    namePt: "Trovao",
    aliases: ["rumble", "trovao", "trovão"],
    rarity: "Legendary",
    type: "Elemental",
    roles: ["pvp", "support"],
    description: "Stuns e combos fortes demais quando bem pilotada.",
    beliPrice: 2100000,
    permRobuxPrice: 2100,
    value: 40000000
  },
  {
    key: "pain",
    name: "Pain",
    namePt: "Dor",
    aliases: ["pain", "dor", "paw", "pata"],
    rarity: "Legendary",
    type: "Natural",
    roles: ["pvp", "support"],
    description: "Niche, mas com potencial tecnico alto.",
    beliPrice: 2300000,
    permRobuxPrice: 2200,
    value: 20000000
  },
  {
    key: "blizzard",
    name: "Blizzard",
    namePt: "Nevasca",
    aliases: ["blizzard", "nevasca"],
    rarity: "Legendary",
    type: "Elemental",
    roles: ["farm", "pvp"],
    description: "Controle de area forte e uso versatil.",
    beliPrice: 2400000,
    permRobuxPrice: 2250,
    value: 5000000
  },
  {
    key: "gravity",
    name: "Gravity",
    namePt: "Gravidade",
    aliases: ["gravity", "gravidade"],
    rarity: "Mythical",
    type: "Natural",
    roles: ["pvp"],
    description: "Visual poderosa, mas abaixo de outras miticas no meta.",
    beliPrice: 2500000,
    permRobuxPrice: 2300,
    value: 15000000
  },
  {
    key: "mammoth",
    name: "Mammoth",
    namePt: "Mamute",
    aliases: ["mammoth", "mamute"],
    rarity: "Mythical",
    type: "Beast",
    roles: ["pvp", "farm"],
    description: "Mitica parruda com boa presenca em combate.",
    beliPrice: 2700000,
    permRobuxPrice: 2350,
    value: 10000000
  },
  {
    key: "trex",
    name: "T-Rex",
    namePt: "T-Rex",
    aliases: ["t-rex", "trex", "t rex"],
    rarity: "Mythical",
    type: "Beast",
    roles: ["pvp", "farm"],
    description: "Bruta, popular e constantemente desejada.",
    beliPrice: 2700000,
    permRobuxPrice: 2350,
    value: 20000000
  },
  {
    key: "dough",
    name: "Dough",
    namePt: "Massa",
    aliases: ["dough", "massa", "mochi"],
    rarity: "Mythical",
    type: "Elemental",
    roles: ["pvp", "farm"],
    description: "Meta historica em PvP e muito valorizada.",
    beliPrice: 2800000,
    permRobuxPrice: 2400,
    value: 30000000
  },
  {
    key: "shadow",
    name: "Shadow",
    namePt: "Sombra",
    aliases: ["shadow", "sombra"],
    rarity: "Mythical",
    type: "Natural",
    roles: ["pvp"],
    description: "Dano pesado e presença marcante em arena.",
    beliPrice: 2900000,
    permRobuxPrice: 2425,
    value: 6500000
  },
  {
    key: "venom",
    name: "Venom",
    namePt: "Veneno",
    aliases: ["venom", "veneno"],
    rarity: "Mythical",
    type: "Natural",
    roles: ["pvp", "farm"],
    description: "Forte, segura e muito respeitada.",
    beliPrice: 3000000,
    permRobuxPrice: 2450,
    value: 10000000
  },
  {
    key: "control",
    name: "Control",
    namePt: "Controle",
    aliases: ["control", "controle", "ctrl"],
    rarity: "Mythical",
    type: "Natural",
    roles: ["pvp", "support"],
    description: "Tecnica, rara e queridinha dos traders.",
    beliPrice: 3200000,
    permRobuxPrice: 2500,
    value: 10000000
  },
  {
    key: "spirit",
    name: "Spirit",
    namePt: "Espirito",
    aliases: ["spirit", "espirito", "espírito", "soul", "alma"],
    rarity: "Mythical",
    type: "Natural",
    roles: ["pvp", "support"],
    description: "Versatil, estilosa e forte em maos treinadas.",
    beliPrice: 3400000,
    permRobuxPrice: 2550,
    value: 10000000
  },
  {
    key: "leopard",
    name: "Leopard",
    namePt: "Leopardo",
    aliases: ["leopard", "leopardo", "leo"],
    rarity: "Mythical",
    type: "Beast",
    roles: ["pvp"],
    description: "Mitica premium com muita pressao ofensiva.",
    beliPrice: 5000000,
    permRobuxPrice: 3000,
    value: 45000000
  },
  {
    key: "kitsune",
    name: "Kitsune",
    namePt: "Kitsune",
    aliases: ["kitsune", "kit", "kitsu"],
    rarity: "Mythical",
    type: "Beast",
    roles: ["pvp", "farm", "travel"],
    description: "Top tier, valiosa e sempre observada pela comunidade.",
    beliPrice: 8000000,
    permRobuxPrice: 4000,
    value: 290000000
  },
  {
    key: "yeti",
    name: "Yeti",
    namePt: "Yeti",
    aliases: ["yeti"],
    rarity: "Mythical",
    type: "Beast",
    roles: ["pvp", "farm"],
    description: "Fruta rara e de alto impacto no meta recente.",
    beliPrice: 5000000,
    permRobuxPrice: 3000,
    value: 160000000
  },
  {
    key: "gas",
    name: "Gas",
    namePt: "Gas",
    aliases: ["gas", "gás"],
    rarity: "Mythical",
    type: "Elemental",
    roles: ["pvp", "support"],
    description: "Fruta moderna com valor alto e muita curiosidade.",
    beliPrice: 3200000,
    permRobuxPrice: 2500,
    value: 75000000
  },
  {
    key: "tiger",
    name: "Tiger",
    namePt: "Tigre",
    aliases: ["tiger", "tigre"],
    rarity: "Mythical",
    type: "Beast",
    roles: ["pvp", "farm"],
    description: "Mitica nova, agressiva e muito cobicada.",
    beliPrice: 5000000,
    permRobuxPrice: 3000,
    value: 55000000
  },
  {
    key: "dragon",
    name: "Dragon",
    namePt: "Dragao",
    aliases: ["dragon", "dragao", "dragão", "dragon east", "dragon west"],
    rarity: "Mythical",
    type: "Beast",
    roles: ["pvp", "farm", "status"],
    description: "Lendaria entre os players, rarissima e alvo numero um de alertas.",
    beliPrice: 3500000,
    permRobuxPrice: 2600,
    value: 1450000000
  }
];
